### ISSUE TITLE
self._menu._top is None

### ISSUE THREAD

**Issue by eforgacs** [ppizarror/pygame-menu#116]
Having an issue with line 145 in menubar.py:
`if not self._menu or not self._menu._top._prev:`
It gives me an `AttributeError: 'NoneType' object has no attribute '_prev'`

However, if I change that line to:
`if not self._menu:`
it runs.

Is there a new parameter or something in version 2.2.0 that I am missing?

**Comment by ppizarror** [comment]
@anxuae did you change something in ._prev? I remember you told me something about this variable

**Comment by ppizarror** [comment]
This was introduced in #89

**Comment by ppizarror** [comment]
maybe the sentence must be changed to "if not self._menu or not (self._menu._top not None and self._menu._top._prev)... but maybe its not necessary

**Comment by anxuae** [comment]
Nothing changed on the `._prev`. But it seems that the `_render()` method of the menubar may be called before `._top` is set.

Condition can be changed in:
```
if not self._menu or not self._menu._top or not self._menu._top._prev:
```

**Comment by eforgacs** [comment]
> Condition can be changed in:
> 
> `if not self._menu or not self._menu._top or not self._menu._top._prev:`

Confirmed, just tried that line,, it works.

**Comment by ppizarror** [comment]
Added to commit pack #115

**Comment by ppizarror** [comment]
This was updated in fix 2.2.1 of the library, uploaded right now
